// project info
const { title, version, author } = require('../package.json');

const banner =
`/*!
 * ${ title } v${ version }
 * https://github.com/MoomFE/ZenJS
 * 
 * (c) 2018 ${ author }
 * Released under the MIT License.
 */
`;



// rollup plugin
const resolve = require('rollup-plugin-node-resolve');
const replace = require('rollup-plugin-replace');
const babel = require('rollup-plugin-babel');

const plugins = [
  resolve(),
  babel({
    exclude: 'node_modules/**'
  }),
  replace({
    __VERSION__: version
  }),
  {
    name: 'Delete void 0 generated by babel',
    transformBundle( code ){
      return code.replace( /\s*=\s*void 0(,|;)/g, '$1' );
    }
  }
];


module.exports = {
  banner,
  plugins
}