import './Array/index';
import './Document/index';
import './Math/index';
import './Number/index';
import './Object/index';
import './String/index';
import './Window/index';
import './shared/global/ZenJS/index';
import './ZenJS/slim';